name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run:  |
          cd test-services
          mvn clean install -DskipTests=true
          
          


      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          cd test-services
          docker build . --file Dockerfile --tag ghcr.io/vsds/testbed-service:1.0.0
          - name: Log in to Docker Hub
          
      - uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          cd test-services
          docker push ghcr.io/vsds/testbed-service:1.0.0