name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          
    - name: Set up JDK and Maven
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run:  |
        cd test-services
        mvn clean install -DskipTests=true


    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file test-services\Dockerfile --tag vsds-testbed-service:$(date +%s)
