name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file test-services/Dockerfile --tag vsds-testbed-service:$(date +%s)
